---
apiVersion: v1
kind: Pod
metadata:
  name: erp
  labels:
    run: erp
spec:
  containers:
    - name: erp
      image: postgres:latest
      env:
        - name: POSTGRES_DB
          value: erp
        - name: POSTGRES_PASSWORD
          value: password
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
