---
apiVersion: v1
kind: Pod
metadata:
  name: hr
  labels:
    run: hr
spec:
  containers:
    - name: hr
      image: mysql:latest
      env:
        - name: MYSQL_DATABASE
          value: hr
        - name: MYSQL_ROOT_PASSWORD
          value: password
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      